FROM node:20.11.1-alpine
ARG API_SERVER
ARG NEXT_PUBLIC_API_SERVER
ARG E2E_TEST
ARG NEXT_PUBLIC_IMAGE_KIT_ID
ARG CMS_SERVER
ARG NEXT_PUBLIC_CMS_SERVER
ARG SHOW_CONSTRUCTION


WORKDIR /app

COPY .npmrc ./
COPY package.json package-lock.json ./
RUN npm install

COPY . .
ENV API_SERVER=$API_SERVER
ENV NEXT_PUBLIC_API_SERVER=$NEXT_PUBLIC_API_SERVER
ENV E2E_TEST=$E2E_TEST
ENV NEXT_PUBLIC_IMAGE_KIT_ID=$NEXT_PUBLIC_IMAGE_KIT_ID
ENV CMS_SERVER=$CMS_SERVER
ENV NEXT_PUBLIC_CMS_SERVER=$NEXT_PUBLIC_CMS_SERVER
ENV SHOW_CONSTRUCTION=$SHOW_CONSTRUCTION
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "dev"]
