export { default as LandingHero } from "./landing-hero";
export { default as LandingServices } from "./landing-services";
export { default as LandingBlogs } from "./landing-blogs";
export { default as LandingEvents } from "./landing-events";
export { default as LandingLinks } from "./landing-links";
export { default as LandingContact } from "./landing-contact";
export { default as Footer } from "./footer";
export { default as BlogsHero } from "./blogs-hero";
export { default as BlogsList } from "./blogs-list";
