# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - hk-dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: hollandkade.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_77636BFF5FF744AFA61F806DB2CFCC26 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_5009425804DB40B8B7762894B5895DB8 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: hollandkade.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_77636BFF5FF744AFA61F806DB2CFCC26 }}/hollandkade/hollandkade/hk-dev-front:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    
    needs: build
    

    steps:
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'hk-dev'
          slot-name: 'Production'
          images: 'hollandkade.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_77636BFF5FF744AFA61F806DB2CFCC26 }}/hollandkade/hollandkade/hk-dev-front:${{ github.sha }}'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0267EB7D17C04893A3941ED45E5B9C2F }}